### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by impunkj** [magespecialist/m2-MSP_AdminRestriction#1]
After Run module get following error.

2 exception(s):
Exception #0 (ReflectionException): Class MSP\SecuritySuiteCommon\Api\UtilsInterface does not exist
Exception #1 (ReflectionException): Class MSP\SecuritySuiteCommon\Api\UtilsInterface does not exist

**Comment by giacmir** [comment]
Hi @impunkj 

Have you installed it with composer? Seems like there is some missing package.

**Comment by impunkj** [comment]
@giacmir 
Directly download

**Comment by giacmir** [comment]
In this case you need to check the composer.json and install every dependency you find under the `require` section. And foreach dependency check if there are other sub-dependencies and install them as well.

This is why the suggested installation method is by using composer that automatically manages all those dependencies for you.
